# Generated by Django 5.0.6 on 2024-05-30 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_customer_date_alter_customer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cno',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
